## 卒業研究　‐　台湾プロ野球の観客動員数予測システム

In [1]:
# code 1
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import tensorflow as tf

# sns.set()
%matplotlib inline

from matplotlib import rcParams
rcParams['font.family'] = 'MS Gothic'

import matplotlib_inline.backend_inline
matplotlib_inline.backend_inline.set_matplotlib_formats('retina')

import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'

### Remarks
#### T：微量 (<0.5mm) precipitation trace amount
#### --：無觀測 no observation

In [9]:
# CSV - 2024 Taoyuan Air Temp.
df_2024_ty_temp = pd.read_csv('./datasets/taoyuan/467050-2024-AirTemperature-day.csv', header=None, sep=',')

df_2024_ty_temp.columns = ['DAY / MONTH', 'JAN', 'FEB', 'MAR', 'APR', 
              'MAY', 'JUN', 'JUL', 'AUG', 
              'SEP', 'OCT', 'NOV', 'DEC']

df_2024_ty_temp = df_2024_ty_temp.iloc[1:].reset_index(drop=True)
df_2024_ty_temp

,DAY / MONTH,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC
0,01,16.9,19.4,11.3,24.1,23.0,26.6,30.1,29.6,30.5,29.0,23.9,18.4
1,02,18.3,17.6,11.3,25.3,21.6,23.1,29.9,29.9,30.3,25.2,23.2,20.3
2,03,15.5,17.4,14.6,26.9,23.2,22.0,29.8,29.8,29.8,23.5,24.1,21.8
3,04,15.3,17.5,16.7,24.5,25.1,24.0,30.3,29.8,31.4,24.0,24.8,20.8
4,05,15.5,16.0,22.8,20.9,25.3,22.9,30.2,29.5,31.1,26.1,22.6,20.2
5,06,16.8,16.1,16.7,21.7,25.9,22.9,29.9,29.3,30.2,27.4,21.8,20.7
6,07,17.2,13.8,13.9,22.2,25.3,24.6,30.2,29.1,29.0,26.6,21.5,18.8
7,08,18.7,12.6,14.1,22.0,24.7,25.9,29.0,29.0,28.4,23.9,22.1,15.9
8,09,17.7,11.7,13.6,19.3,22.6,26.7,29.1,29.6,28.9,23.7,22.9,18.1
9,10,16.0,13.2,16.9,21.9,24.6,28.0,29.6,29.3,27.8,23.7,23.3,19.0
10,11,13.8,15.3,15.7,23.3,24.6,28.8,29.9,29.8,28.8,24.3,23.2,19.1
11,12,14.7,17.3,17.1,23.4,25.8,29.0,30.3,30.0,29.8,25.7,23.6,17.8
12,13,17.2,14.6,18.8,24.6,19.2,29.4,30.4,29.8,29.4,27.2,24.6,16.3
13,14,18.0,17.0,17.9,24.4,21.0,28.8,30.5,28.8,26.9,26.7,24.4,13.5
14,15,16.1,18.7,17.3,26.2,22.0,29.0,30.5,27.4,28.0,26.9,24.4,13.9
15,16,17.5,14.3,18.3,25.3,22.1,28.7,30.3,28.3,30.0,26.6,23.2,14.9
16,17,18.7,15.5,19.9,25.8,23.3,28.9,30.3,28.1,31.0,27.0,23.1,17.2
17,18,19.0,19.2,17.3,23.3,24.5,28.6,30.5,29.1,28.4,26.6,20.5,15.5
18,19,19.6,22.4,14.6,23.8,25.8,28.7,30.3,29.4,28.4,26.8,20.0,13.4
19,20,18.4,23.5,16.2,26.0,25.8,29.0,30.6,29.1,29.2,24.6,20.6,16.2
20,21,14.3,23.9,19.0,26.0,25.5,29.8,30.8,29.3,26.5,25.8,19.5,15.4
21,22,11.4,18.3,20.5,25.3,24.2,29.9,32.1,29.7,26.5,25.5,20.0,13.6
22,23,8.1,14.4,23.4,25.5,24.2,30.1,30.9,28.7,26.9,22.3,20.5,15.9
23,24,10.6,14.5,24.7,21.4,24.9,29.5,28.6,28.8,27.5,21.9,21.3,16.8
24,25,11.3,13.0,24.9,22.9,25.9,28.9,27.7,28.7,27.4,25.1,22.4,17.8
25,26,13.1,12.7,20.6,24.0,26.1,29.7,27.8,28.8,27.3,26.4,18.8,17.3
26,27,13.6,13.5,20.1,25.5,27.1,30.0,29.1,29.5,26.7,26.7,17.3,17.0
27,28,13.7,15.6,23.3,26.3,23.6,29.8,29.8,29.4,27.1,23.6,16.9,13.2
28,29,17.6,16.6,23.5,27.3,23.6,30.2,29.3,29.6,28.3,22.8,16.1,15.8
29,30,16.8,--,23.7,26.0,26.5,30.4,28.6,29.6,28.6,23.0,17.5,16.1
30,31,18.6,--,24.3,--,28.1,--,28.9,30.0,--,25.9,--,16.3
31,平均,15.8,16.4,18.5,24.2,24.4,27.8,29.8,29.3,28.7,25.3,21.6,17.0

In [10]:
# CSV - 2024 Taoyuan .
df_2024_ty_temp = pd.read_csv('./datasets/taoyuan/467050-2024-Precipitation-day.csv', header=None, sep=',')

df_2024_ty_temp.columns = ['DAY / MONTH', 'JAN', 'FEB', 'MAR', 'APR', 
              'MAY', 'JUN', 'JUL', 'AUG', 
              'SEP', 'OCT', 'NOV', 'DEC']

df_2024_ty_temp = df_2024_ty_temp.iloc[1:].reset_index(drop=True)
df_2024_ty_temp

,DAY / MONTH,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC
0,01,0.0,0.0,13.0,4.5,19.0,6.5,0.0,0.0,0.0,1.5,24.0,0.0
1,02,0.0,T,6.0,0.0,4.0,99.5,0.0,0.0,0.0,5.0,0.0,0.0
2,03,T,T,T,0.0,0.0,2.5,0.0,0.0,0.0,3.0,0.0,0.0
3,04,0.0,1.5,0.0,T,0.0,T,0.0,0.0,0.0,15.5,0.0,0.0
4,05,0.0,26.0,0.0,T,1.5,47.0,0.0,0.0,0.0,1.5,1.5,0.0
5,06,0.0,0.0,10.5,5.0,0.0,5.5,0.0,0.0,T,0.0,T,0.0
6,07,0.0,17.0,17.5,8.5,0.0,1.0,0.0,T,2.0,10.0,0.0,0.5
7,08,T,5.5,0.0,16.0,0.0,0.0,T,T,29.0,15.5,T,3.5
8,09,6.5,10.0,T,0.5,0.0,0.0,0.0,T,0.0,1.5,5.5,T
9,10,0.0,0.0,T,0.0,0.0,0.0,0.0,T,23.5,0.0,1.0,0.0
10,11,0.0,0.0,25.0,0.0,0.0,T,0.0,0.0,0.0,0.0,1.0,T
11,12,0.0,0.0,2.0,0.0,15.5,0.0,0.0,0.0,0.0,0.0,5.0,0.5
12,13,0.0,0.0,0.0,0.0,19.5,0.0,0.0,0.0,0.0,0.0,0.0,6.0
13,14,0.0,0.0,T,0.0,0.0,14.5,0.0,19.5,2.5,0.0,0.0,T
14,15,T,0.0,T,0.0,0.0,0.0,0.0,17.0,0.0,0.0,0.0,0.0
15,16,T,0.5,T,T,0.0,0.0,0.0,T,0.0,T,4.0,T
16,17,0.0,0.0,T,T,0.0,T,0.0,0.0,0.0,0.0,5.5,0.0
17,18,0.0,0.0,T,22.5,0.0,0.0,0.0,0.0,*16.5,0.0,1.5,0.0
18,19,0.0,0.0,3.5,T,0.0,4.5,0.0,0.0,0.0,T,0.5,T
19,20,1.0,T,0.0,0.0,T,0.0,0.0,T,0.0,0.5,1.0,0.5
20,21,2.5,0.0,0.0,0.0,1.5,0.0,0.0,0.0,189.0,T,21.0,T
21,22,16.0,0.0,0.0,3.0,0.5,0.0,0.0,0.0,25.0,T,T,0.0
22,23,14.0,T,0.0,1.5,13.5,0.0,T,0.0,23.0,6.0,0.0,9.0
23,24,0.0,T,2.0,55.0,3.5,0.0,38.5,0.0,9.5,11.0,0.0,1.0
24,25,2.5,0.5,0.0,6.0,T,6.5,42.5,0.0,T,6.0,0.0,2.0
25,26,0.0,0.5,0.0,46.0,1.0,0.0,13.5,T,6.0,T,0.5,1.5
26,27,T,0.5,0.0,6.0,1.5,0.0,T,0.0,7.0,0.0,0.0,T
27,28,T,T,0.0,0.5,58.5,0.0,T,0.0,8.0,0.5,0.0,0.5
28,29,0.5,1.0,0.0,0.0,0.0,0.0,6.5,0.0,T,1.0,0.0,0.0
29,30,T,--,4.0,15.0,0.0,0.0,T,0.0,0.0,5.0,0.0,0.0
30,31,0.0,--,67.5,--,T,--,0.5,0.0,--,87.5,--,0.0
31,總和,43.0,63.0,151.0,190.0,139.5,187.5,101.5,36.5,*341.0,171.0,72.0,25.0